version: "3"
services:
  application:
    image: onetomanyApp-mysql-docker-app
    ports:
      - "8085:8088"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    
  mysqldb:
    image: mysql:8.0
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mapping
    volumes:
      - /data/mysql
networks:
  springboot-db-net: