
server:
  port: 8088
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/mapping
    #configure the db name that is running in another machine
   # url: jdbc:mysql://localhost:3306/mapping
    username: root
    password: Parshuram@1727
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  